basePath: /v1
definitions:
  main.ChangeRoleRequest:
    properties:
      role:
        enum:
        - viewer
        - analyst
        - admin
        type: string
    required:
    - role
    type: object
  main.ChangeStatusRequest:
    properties:
      is_active:
        type: boolean
    required:
    - is_active
    type: object
  main.CreateRecordRequest:
    properties:
      amount:
        type: number
      category:
        maxLength: 50
        type: string
      description:
        maxLength: 500
        type: string
      entry_date:
        type: string
      target_user_id:
        type: integer
      type:
        enum:
        - income
        - expense
        type: string
    required:
    - amount
    - category
    - entry_date
    - target_user_id
    - type
    type: object
  main.LoginUserPayload:
    properties:
      password:
        maxLength: 72
        minLength: 3
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - password
    - username
    type: object
  main.UserPayload:
    properties:
      email:
        maxLength: 255
        type: string
      first_name:
        maxLength: 100
        type: string
      last_name:
        maxLength: 100
        type: string
      password:
        maxLength: 72
        minLength: 3
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - first_name
    - last_name
    - password
    - username
    type: object
  storage.FinancialRecord:
    properties:
      amount:
        type: number
      category:
        type: string
      created_at:
        type: string
      description:
        type: string
      entry_date:
        type: string
      id:
        type: integer
      type:
        type: string
      user_id:
        type: integer
    type: object
  storage.Trend:
    properties:
      date:
        type: string
      total_expense:
        type: number
      total_income:
        type: number
    type: object
  storage.User:
    properties:
      created_at:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      is_active:
        type: boolean
      last_name:
        type: string
      role:
        type: string
      username:
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  title: Finance API Backend
  version: "1.0"
paths:
  /finance/create_record:
    post:
      consumes:
      - application/json
      description: Add a new income or expense entry. Only Admin.
      parameters:
      - description: Record details
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.CreateRecordRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            additionalProperties: true
            type: object
        "400":
          description: Bad payload
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Create a financial record
      tags:
      - finance
  /finance/delete_record/{recordID}:
    delete:
      description: Deletes a financial record from the system by its ID.
      parameters:
      - description: Record ID
        in: path
        name: recordID
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: record deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad payload
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Delete a financial record
      tags:
      - finance
  /finance/list_records:
    get:
      description: Get financial entries for current user with optional filters
      parameters:
      - description: Filter by category
        in: query
        name: category
        type: string
      - description: Filter by type (income/expense)
        in: query
        name: type
        type: string
      - description: Start date (YYYY-MM-DD)
        in: query
        name: from
        type: string
      - description: End date (YYYY-MM-DD)
        in: query
        name: to
        type: string
      - description: Result offset
        in: query
        name: offset
        type: string
      - description: Result limit
        in: query
        name: limit
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.FinancialRecord'
            type: array
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: List financial records
      tags:
      - finance
  /finance/summary:
    get:
      consumes:
      - application/json
      description: Returns aggregated totals (income, expense, balance) and the 5
        most recent records
      produces:
      - application/json
      responses:
        "200":
          description: Returns TotalIncome, TotalExpense, NetBalance and RecentRecords
          schema:
            additionalProperties: true
            type: object
        "401":
          description: Unauthorized
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Get financial dashboard summary
      tags:
      - finance
  /finance/trends:
    get:
      parameters:
      - description: Months back
        in: query
        name: months_back
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.Trend'
            type: array
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Retrieves financial trends
      tags:
      - finance
  /finance/update_record/{recordID}:
    put:
      consumes:
      - application/json
      description: Updates a financial record by its ID. Only accessible by admins.
      parameters:
      - description: Record ID
        in: path
        name: recordID
        required: true
        type: integer
      - description: Update Record Request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/main.CreateRecordRequest'
      produces:
      - application/json
      responses:
        "200":
          description: record updated successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Bad payload
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Update an existing financial record
      tags:
      - finance
  /health:
    get:
      description: Checks if the server is active.
      responses:
        "200":
          description: OK
      summary: Health check
      tags:
      - utils
  /users:
    get:
      description: Returns a list of all registered users in the system. Only accessible
        by Admin.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      tags:
      - users
  /users/{id}:
    delete:
      description: Permanently removes a user from the system by their ID. Only accessible
        by Admin.
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: user deleted successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid user ID
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Delete a user
      tags:
      - users
  /users/{id}/role:
    patch:
      consumes:
      - application/json
      description: Allows an admin to change a user's access level (admin, analyst,
        viewer)
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: New role name
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.ChangeRoleRequest'
      produces:
      - application/json
      responses:
        "200":
          description: user role updated successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid role or ID
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Update user role
      tags:
      - users
  /users/{id}/status:
    patch:
      consumes:
      - application/json
      description: Allows an admin to activate or deactivate a user account
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      - description: 'New status (is_active: true/false)'
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.ChangeStatusRequest'
      produces:
      - application/json
      responses:
        "200":
          description: user status updated successfully
          schema:
            additionalProperties:
              type: string
            type: object
        "400":
          description: Invalid request payload or ID
          schema: {}
        "401":
          description: Unauthorized
          schema: {}
        "403":
          description: Forbidden - Admin only
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Update user status
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Authenticates a user and returns a JWT.
      parameters:
      - description: Login credentials (username, password)
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.LoginUserPayload'
      produces:
      - application/json
      responses:
        "200":
          description: JWT Token
          schema:
            type: string
        "401":
          description: Invalid credentials
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: User login
      tags:
      - auth
  /users/me:
    get:
      description: Returns the profile information and role of the currently authenticated
        user based on the JWT token
      produces:
      - application/json
      responses:
        "200":
          description: Successfully retrieved user profile
          schema:
            $ref: '#/definitions/storage.User'
        "401":
          description: Unauthorized - Invalid or missing token
          schema: {}
        "500":
          description: Internal server error
          schema: {}
      security:
      - BearerAuth: []
      summary: Get current user information
      tags:
      - users
  /users/register:
    post:
      consumes:
      - application/json
      description: Creates a new user account.
      parameters:
      - description: User registration data (email, username, password, device_id,
          push_token)
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/main.UserPayload'
      produces:
      - application/json
      responses:
        "201":
          description: User created successfully
          schema:
            type: nil
        "400":
          description: User already exists
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error during hashing or database insert
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Register a new user
      tags:
      - auth
securityDefinitions:
  BearerAuth:
    description: Type "Bearer <your-jwt-token>"
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
